theme: jekyll-theme-cayman

title: Sudipto Das
description: Engineer and Researcher with passion for Scalable Distributed Database Systems

google_analytics: UA-11144700-3


show_header_links: "true"
pubs_page: publications
serivce_page: service
