theme: jekyll-theme-cayman

title: Sudipto Das
description: Engineer and Researcher with expertise in building Scalable Distributed Database Systems

google_analytics: G-NTHGZPKVSB


show_header_links: "true"
pubs_page: publications
serivce_page: service
